//
//  UIColor+BLColors.m
//  Bond Light
//
//  Generated by Zeplin (by bd452 on 2/7/15).
//  Copyright (c) 2015 __MyCompanyName__. All rights reserved.
//

#import "UIColor+BLColors.h"

@implementation UIColor (BLColors)

+ (UIColor *)bl_doveGrayColor {
    return [UIColor colorWithRed:103.0f / 255.0f
                           green:103.0f / 255.0f
                            blue:103.0f / 255.0f
                           alpha:1.0f];
}

+ (UIColor *)bl_doveGray1Color {
    return [UIColor colorWithRed:110.0f / 255.0f
                           green:110.0f / 255.0f
                            blue:110.0f / 255.0f
                           alpha:1.0f];
}

+ (UIColor *)bl_mineShaftColor {
    return [UIColor colorWithRed:64.0f / 255.0f
                           green:64.0f / 255.0f
                            blue:64.0f / 255.0f
                           alpha:1.0f];
}

+ (UIColor *)bl_silverChaliceColor {
    return [UIColor colorWithRed:173.0f / 255.0f
                           green:173.0f / 255.0f
                            blue:173.0f / 255.0f
                           alpha:1.0f];
}

+ (UIColor *)bl_whiteColor {
    return [UIColor colorWithRed:255.0f / 255.0f
                           green:255.0f / 255.0f
                            blue:255.0f / 255.0f
                           alpha:1.0f];
}

+ (UIColor *)bl_azureRadianceColor {
    return [UIColor colorWithRed:0.0f / 255.0f
                           green:164.0f / 255.0f
                            blue:255.0f / 255.0f
                           alpha:1.0f];
}

+ (UIColor *)bl_lochmaraColor {
    return [UIColor colorWithRed:0.0f / 255.0f
                           green:137.0f / 255.0f
                            blue:213.0f / 255.0f
                           alpha:1.0f];
}

+ (UIColor *)bl_backgroundColorColor {
    return [UIColor colorWithRed:241.0f / 255.0f
                           green:241.0f / 255.0f
                            blue:241.0f / 255.0f
                           alpha:1.0f];
}

+ (UIColor *)bl_altoColor {
	return [UIColor colorWithRed:215.0f / 255.0f
						   green:215.0f / 255.0f
							blue:215.0f / 255.0f
						   alpha:1.0f];
}

+ (UIColor *)bl_azureNightColor {
	return [UIColor colorWithRed:0.0f / 255.0f
						   green:139.0f / 255.0f
							blue:217.0f / 255.0f
						   alpha:1.0f];
}

@end
